"use client";

import { motion } from "framer-motion";

const TermsAndConditions = () => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 50 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -50 }}
      transition={{ duration: 0.5 }}
      className="max-w-4xl mx-auto px-6 py-10 bg-white rounded-lg shadow-md mt-24">
      <h1 className="text-4xl font-bold text-gray-800 mb-8">
        Terms and Conditions
      </h1>
      <div className="space-y-6 text-lg text-gray-700">
        <section>
          <h2 className="text-2xl font-semibold mb-2">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing and using the chatbot services on{" "}
            <strong>gregdavistech</strong>, you agree to be bound by these Terms
            and Conditions. If you do not agree with any part of these terms,
            you must stop using the Website.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-2">2. Services</h2>
          <p>
            The Website provides users with access to a chatbot powered by
            OpenAI. By using the chatbot, you agree to abide by all applicable
            rules set by OpenAI.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-2">3. Account Creation</h2>
          <p>
            Users may create an account by providing their name, email address,
            and profile image. It is your responsibility to provide accurate
            information and keep your account secure.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-2">4. Prohibited Uses</h2>
          <p>
            Users must not use the chatbot in any way that violates applicable
            laws or OpenAI’s guidelines. The Website reserves the right to
            terminate accounts found in violation.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-2">
            5. User-Generated Content
          </h2>
          <p>
            Conversations may be stored for service improvement.{" "}
            <strong>gregdavistech</strong> does not claim ownership over content
            generated by users.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-2">
            6. Termination of Service
          </h2>
          <p>
            The Website reserves the right to suspend or terminate any user’s
            access if they violate these Terms or OpenAI’s policies.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-2">7. Modifications</h2>
          <p>
            <strong>gregdavistech</strong> reserves the right to modify these
            Terms at any time. Significant changes will be communicated to
            users.
          </p>
        </section>
      </div>
    </motion.div>
  );
};

export default TermsAndConditions;
